
# Colors (Gruvbox dark)
[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"


# Font configuration
[font]
size = 13.0

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"


# Key
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true
