
### black
# fmt: on/off
[tool.black]
line-length = 88
indent-width = 4
skip-string-normalization = false


### ruff
# fmt: on/off
[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py310"

[tool.ruff.format]
preview = true
quote-style = "double" # "single"
indent-style = "space" # "tab"


### pyright
# Only enable pyright or basedpyright
# [tool.pyright]
# typeCheckingMode = 'standard' # "off", "basic", "standard", "strict"
#
# [[tool.pyright.executionEnvironments]]
# root = "."
# extraPaths = ["src", "../lib"]


### basedpyright
[tool.basedpyright]
typeCheckingMode = 'standard' # "off", "basic", "standard", "strict", "all"
reportAny = false

[[tool.basedpyright.executionEnvironments]]
root = "."
extraPaths = ["src", "../lib"]
