
string(ASCII 27 Esc)
set(ColorReset  "${Esc}[m")
set(ColorBold   "${Esc}[1m")
set(Red         "${Esc}[31m")
set(Green       "${Esc}[32m")
set(Yellow      "${Esc}[33m")
set(Blue        "${Esc}[34m")
set(Magenta     "${Esc}[35m")
set(Cyan        "${Esc}[36m")
set(White       "${Esc}[37m")
set(BoldRed     "${Esc}[1;31m")
set(BoldGreen   "${Esc}[1;32m")
set(BoldYellow  "${Esc}[1;33m")
set(BoldBlue    "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan    "${Esc}[1;36m")
set(BoldWhite   "${Esc}[1;37m")


# Color message macro
macro(cmsg)
    # ARGV is replacements(also access via ${} though), not variable
    set(Args "${ARGV}")

    list(GET Args 0 Mode)
    if(Mode STREQUAL ERROR)
        set(Mode FATAL_ERROR)
    elseif(Mode STREQUAL INFO)
        set(Mode STATUS)
    endif()

    if((Mode STREQUAL FATAL_ERROR) OR (Mode STREQUAL SEND_ERROR))
        list(REMOVE_AT Args 0)
        message(${Mode} "${BoldRed}${Args}${ColorReset}")
    elseif(Mode STREQUAL WARNING)
        list(REMOVE_AT Args 0)
        message(${Mode} "${BoldYellow}${Args}${ColorReset}")
    elseif(Mode STREQUAL STATUS)
        list(REMOVE_AT Args 0)
        message(${Mode} "${Green}${Args}${ColorReset}")
    else()
        message("${Args}")
    endif()
endmacro()
