source $APPS_HOME/dotvim/init/viml/init.vim

if IsWin()
    set pythonthreedll=python311.dll
    let s:use = SvarUse()
    let s:use.ui.font = 'Consolas For Powerline'
    let s:use.ui.wide = 'Microsoft YaHei Mono'
    call GuiSetFonts(0)
endif
